# Experiment settings
base_config: neumeta/config/base_config.yaml

experiment:
  name: ninr_resnet32_cifar10_32-64-4layer-50e-noisecoord-resmlpv2_smooth_5_256_16_positional_encoding
  num_epochs: 50
  log_interval: 100
  seed: 42  # Random seed

# Model configurations
model:
  type: ResNet32
  pretrained_path: toy/checkpoint/cifar10_ResNet32_smooth_Ours.pth  # Path to pre-trained model
  # smooth: True

# Training configurations
training:
  learning_rate: 1e-3
  batch_size: 64
  coordinate_noise: 1.0
  noise_type: 'uniform'
  lr_steps: [100, 150]
  weight_decay: 1e-2
  clip_grad: 10.0
  save_model_path: toy/experiments/resnet32_cifar10_32-64-4layer-50e-noisecoord-resmlpv2_smooth_5_256_16_positional_encoding # Directory to save the trained model

# Hyper-model specifications (specific to NeRF)
hyper_model:
  type: resmlp_pe
  input_dim: 6
  hidden_dim: 256
  num_layers: 5
  num_freqs: 16
  output_dim: 9
  ema_decay: 0.995  # Exponential moving average decay

# Experiment dimensions configuration
dimensions:
  range: [32, 64]  # Dimension range for the experiment
  test: 32  # Testing dimension
  norm: 64  # Normalization factor
  start: 64  # Starting dimension
